gcs:
  staging_bucket: "siteselect-dbt"
  staging_prefix: "staged/"

scan:
  source_prefix: "gs://siteselect-dbt/rextagsource/data_drop=2026-01/"
  dbt_output_dir: "dbt_project/models/staging/"

sources:
  - name: "county_parcels"
    uri: "gs://siteselect-dbt/rextagsource/data_drop=2026-01/county_parcels.zip"
  - name: "zoning_data"
    uri: "gs://siteselect-dbt/rextagsource/data_drop=2026-01/zoning_data.zip"
